# -*- coding: utf-8 -*-
"""Merge Sorted Array.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cfQQA7P8nWwLgQmGOf-vJbmh_dwLMvK7
"""

class Solution:
    def merge(self, nums1: List[int], m: int, nums2: List[int], n: int) -> None:
        """
        Do not return anything, modify nums1 in-place instead.
        """
        nums1[m : m+n] = nums2
        return nums1.sort()

def merge(self, nums1: List[int], m: int, nums2: List[int], n: int) -> None:
    while n > 0:
        if nums1[m-1] >= nums2[n-1] and m>0:
            nums1[m+n-1] = nums1[m-1]
            m -= 1
        else:
            nums1[m+n-1] = nums2[n-1]
            n -= 1