# -*- coding: utf-8 -*-
"""Plus One.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cfQQA7P8nWwLgQmGOf-vJbmh_dwLMvK7
"""

class Solution:
    def plusOne(self, digits: List[int]) -> List[int]:
        answer = []
        s = ''.join([str(n) for n in digits])
        new = str(int(s) + 1)
        for i in new:
            answer.append(int(i))

        return answer