# -*- coding: utf-8 -*-
"""leetcode.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19sP258Wi-6r79zMk0lHUi2-EIX-amQ_I
"""

class Solution:
    def removeDuplicates(self, nums):
        curr = 1
        for i in range(len(nums)-1):
            if nums[i+1] != nums[i]:
                nums[curr] = nums[i+1]
                curr += 1
        return curr