# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cfQQA7P8nWwLgQmGOf-vJbmh_dwLMvK7
"""

class Solution:
    def strStr(self, haystack: str, needle: str) -> int:
        words = {}
        for i in reversed(range(len(haystack)-len(needle)+1)):
            words[haystack[i:(i+len(needle))]] = i
        if needle in words:
            return words[needle]
        else:
            return -1