# -*- coding: utf-8 -*-
"""leetcode.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19sP258Wi-6r79zMk0lHUi2-EIX-amQ_I
"""

class Solution:
    def longestCommonPrefix(self, strs: List[str]) -> str:
        strs.sort(key = len)
        for i, v in enumerate(strs[0]):
            for j in strs:
                if j[i] != v:
                    return strs[0][:i]
        return strs[0]