# -*- coding: utf-8 -*-
"""leetcode.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19sP258Wi-6r79zMk0lHUi2-EIX-amQ_I
"""

class Solution:
    def isValid(self, s: str) -> bool:
        match = {')': '(', ']': '[', '}': '{'}
        stack = []
        for i in s:
            if i in '([{':
                stack.append(i)
            elif i in match:
                if len(stack) == 0:
                    return False
                else:
                    t = stack.pop()
                    if t != match[i]:
                        return False
        return len(stack) == 0