# -*- coding: utf-8 -*-
"""Sqrt(x).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cfQQA7P8nWwLgQmGOf-vJbmh_dwLMvK7
"""

class Solution:
    def mySqrt(self, x: int) -> int:
        answer = 0
        while answer >= 0:
            if x >= answer*answer and x < (answer+1)*(answer+1):
                return answer
            answer += 1