# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jfFEZSEUOtuvew20IgnvZUoO5gS8HWsm
"""

class Solution:
    def climbStairs(self, n: int) -> int:
        if n <= 2:
            return n
        else:
            a, b = 1, 2
            for i in range(n-2):
                a, b = b, a+b
        return b